---------------------------------------------------
-- Housing Completed - ImportedSources.lua
-- Generated by tools/Import-WowDbDecor.ps1
---------------------------------------------------
local addonName, HC = ...

HC.ImportedDecorItems = HC.ImportedDecorItems or {}

