---------------------------------------------------
-- Housing Completed - ImportedAllItems.lua
-- Generated by tools/Import-WowDbDecor.ps1
---------------------------------------------------
local addonName, HC = ...

HC.ImportedAllItems = HC.ImportedAllItems or {}
HC.ImportedAllItems.IDs = HC.ImportedAllItems.IDs or {}

