param(
    [Parameter(Mandatory = $true)]
    [string]$InputCsv,
    [string]$OutputSources = "Data/ImportedSources.lua",
    [string]$OutputAllItems = "Data/ImportedAllItems.lua"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if (-not (Test-Path $InputCsv)) {
    throw "Input CSV not found: $InputCsv"
}

function Get-FieldValue {
    param(
        [pscustomobject]$Row,
        [string[]]$Names
    )
    foreach ($n in $Names) {
        if ($Row.PSObject.Properties.Name -contains $n) {
            $v = $Row.$n
            if ($null -ne $v -and "$v".Trim() -ne "") {
                return "$v".Trim()
            }
        }
    }
    return $null
}

function Escape-LuaString {
    param([string]$Value)
    if ($null -eq $Value) { return $null }
    $v = $Value.Replace("\", "\\").Replace('"', '\"')
    return '"' + $v + '"'
}

function To-NumberOrNull {
    param([string]$Value)
    if ($null -eq $Value) { return $null }
    $trimmed = $Value.Trim()
    if ($trimmed -eq "") { return $null }
    $num = 0.0
    if ([double]::TryParse($trimmed, [Globalization.NumberStyles]::Float, [Globalization.CultureInfo]::InvariantCulture, [ref]$num)) {
        return $num
    }
    return $null
}

$rows = Import-Csv -Path $InputCsv
$importedDecor = New-Object System.Collections.Generic.List[object]
$allItemIDs = New-Object "System.Collections.Generic.HashSet[int]"
$seenPairs = New-Object "System.Collections.Generic.HashSet[string]"

foreach ($row in $rows) {
    $name = Get-FieldValue $row @("name", "itemName", "item_name", "item")
    $itemIdRaw = Get-FieldValue $row @("itemID", "itemId", "item_id", "id")
    $itemID = 0
    $hasItemID = [int]::TryParse($itemIdRaw, [ref]$itemID)

    if ((-not $name) -and (-not $hasItemID)) { continue }

    $sourceType = (Get-FieldValue $row @("sourceType", "source_type", "type", "category"))
    if (-not $sourceType) { $sourceType = "unknown" }
    $source = Get-FieldValue $row @("source", "requirement", "achievement", "quest")
    $vendor = Get-FieldValue $row @("vendor", "vendorName", "vendor_name", "npc", "npcName")
    $cost = Get-FieldValue $row @("cost", "price")
    $zone = Get-FieldValue $row @("zone", "location")
    $mapIDRaw = Get-FieldValue $row @("mapID", "mapId", "map_id")
    $mapID = 0
    $hasMapID = [int]::TryParse($mapIDRaw, [ref]$mapID)
    $xNum = To-NumberOrNull (Get-FieldValue $row @("x", "coordX", "coord_x"))
    $yNum = To-NumberOrNull (Get-FieldValue $row @("y", "coordY", "coord_y"))
    $faction = Get-FieldValue $row @("faction")
    $expansion = Get-FieldValue $row @("expansion")
    $notes = Get-FieldValue $row @("notes", "note")
    $standing = Get-FieldValue $row @("standing")
    $profession = Get-FieldValue $row @("profession")

    $namePart = ""
    if ($name) { $namePart = $name }
    $idPart = 0
    if ($hasItemID) { $idPart = $itemID }
    $pairKey = ("{0}|{1}" -f $namePart, $idPart).ToLowerInvariant()
    if ($seenPairs.Contains($pairKey)) { continue }
    [void]$seenPairs.Add($pairKey)

    if ($hasItemID -and $itemID -gt 0) {
        [void]$allItemIDs.Add($itemID)
    }

    $importedDecor.Add([pscustomobject]@{
        name = $name
        itemID = $(if ($hasItemID -and $itemID -gt 0) { $itemID } else { $null })
        sourceType = $sourceType
        source = $source
        vendor = $vendor
        cost = $cost
        zone = $zone
        x = $xNum
        y = $yNum
        mapID = if ($hasMapID -and $mapID -gt 0) { $mapID } else { $null }
        faction = $faction
        expansion = $expansion
        notes = $notes
        standing = $standing
        profession = $profession
    }) | Out-Null
}

$sourceLines = New-Object System.Collections.Generic.List[string]
$sourceLines.Add("---------------------------------------------------") | Out-Null
$sourceLines.Add("-- Housing Completed - ImportedSources.lua") | Out-Null
$sourceLines.Add("-- Generated by tools/Import-WowDbDecor.ps1") | Out-Null
$sourceLines.Add("---------------------------------------------------") | Out-Null
$sourceLines.Add("local addonName, HC = ...") | Out-Null
$sourceLines.Add("") | Out-Null
$sourceLines.Add("HC.ImportedDecorItems = {") | Out-Null

foreach ($item in $importedDecor) {
    $parts = New-Object System.Collections.Generic.List[string]
    if ($item.name) { $parts.Add("name = $(Escape-LuaString $item.name)") | Out-Null }
    if ($item.itemID) { $parts.Add("itemID = $($item.itemID)") | Out-Null }
    if ($item.sourceType) { $parts.Add("sourceType = $(Escape-LuaString $item.sourceType)") | Out-Null }
    if ($item.source) { $parts.Add("source = $(Escape-LuaString $item.source)") | Out-Null }
    if ($item.vendor) { $parts.Add("vendor = $(Escape-LuaString $item.vendor)") | Out-Null }
    if ($item.cost) { $parts.Add("cost = $(Escape-LuaString $item.cost)") | Out-Null }
    if ($item.zone) { $parts.Add("zone = $(Escape-LuaString $item.zone)") | Out-Null }
    if ($item.x -ne $null -and $item.y -ne $null) {
        $x = [string]::Format([Globalization.CultureInfo]::InvariantCulture, "{0:0.###}", $item.x)
        $y = [string]::Format([Globalization.CultureInfo]::InvariantCulture, "{0:0.###}", $item.y)
        $parts.Add("coords = {$x, $y}") | Out-Null
    }
    if ($item.mapID) { $parts.Add("mapID = $($item.mapID)") | Out-Null }
    if ($item.faction) { $parts.Add("faction = $(Escape-LuaString $item.faction)") | Out-Null }
    if ($item.expansion) { $parts.Add("expansion = $(Escape-LuaString $item.expansion)") | Out-Null }
    if ($item.notes) { $parts.Add("notes = $(Escape-LuaString $item.notes)") | Out-Null }
    if ($item.standing) { $parts.Add("standing = $(Escape-LuaString $item.standing)") | Out-Null }
    if ($item.profession) { $parts.Add("profession = $(Escape-LuaString $item.profession)") | Out-Null }

    $sourceLines.Add("    { " + ($parts -join ", ") + " },") | Out-Null
}

$sourceLines.Add("}") | Out-Null

$idLines = New-Object System.Collections.Generic.List[string]
$idLines.Add("---------------------------------------------------") | Out-Null
$idLines.Add("-- Housing Completed - ImportedAllItems.lua") | Out-Null
$idLines.Add("-- Generated by tools/Import-WowDbDecor.ps1") | Out-Null
$idLines.Add("---------------------------------------------------") | Out-Null
$idLines.Add("local addonName, HC = ...") | Out-Null
$idLines.Add("") | Out-Null
$idLines.Add("HC.ImportedAllItems = HC.ImportedAllItems or {}") | Out-Null
$idLines.Add("HC.ImportedAllItems.IDs = {") | Out-Null

$sortedIDs = $allItemIDs.ToArray()
[array]::Sort($sortedIDs)
foreach ($id in $sortedIDs) {
    $idLines.Add("    $id,") | Out-Null
}
$idLines.Add("}") | Out-Null

$sourceLines | Set-Content -Path $OutputSources -Encoding UTF8
$idLines | Set-Content -Path $OutputAllItems -Encoding UTF8

Write-Output ("Imported {0} source rows and {1} unique itemIDs." -f $importedDecor.Count, $sortedIDs.Count)
Write-Output ("Wrote: {0}" -f $OutputSources)
Write-Output ("Wrote: {0}" -f $OutputAllItems)
